name: TestCI

on:
  pull_request:
    branches: [ $default-branch ]
  workflow_dispatch:
jobs:
  test:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - run: npm install
      - run: npm test
